{% set name = "eva-lcd" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eva_lcd-{{ version }}.tar.gz
  sha256: 96f014114cd125ebf45a70a20b9ad469ead65b336696bddee43ed11083cb3772

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - networkx >=2.4

test:
  imports:
    - Eva
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GiulioRossetti/eva
  summary: 'Eva: Community Discovery for labeled graphs'
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
